In [1]:
import os
import sys
import yaml
import argparse
from box import Box
import numpy as np
import torch

abs_path = os.path.abspath("..")
sys.path.append(abs_path)

from utils import load_params_yaml, set_gpu
from train import load_defaults_from_yaml

config_file = os.path.join(abs_path, "params.yaml")

params = load_defaults_from_yaml(config_file)
test = Box(params)
args = test
args.pin_memory = True if not torch.mps.is_available() else False

In [2]:
from dataloader.data_utils import get_dataloader, set_up_datasets

In [3]:
args.gpu = "0"
args = set_up_datasets(args)
args.num_gpu = set_gpu(args)

use gpu: [0]


In [4]:
dataroot = os.path.join(abs_path, args.dataroot)
print(dataroot)
args.dataroot = dataroot

/app/data


In [5]:
args

Box({'device': 'cuda', 'gpu': '0', 'seed': 1, 'normalize_method': 'moving_minmax', 'project': 'fact', 'dataset': 'CICIDS2017_improved', 'dataroot': '/app/data', 'encoder': 'cnn1d', 'base_mode': 'ft_cos', 'new_mode': 'avg_cos', 'epochs_base': 1, 'epochs_new': 1000, 'batch_size_base': 128, 'test_batch_size': 100, 'start_session': 0, 'lr_base': 0.005, 'lr_new': 0.01, 'schedule': 'Step', 'milestones': [60, 70], 'step': 20, 'decay': 0.0005, 'momentum': 0.9, 'gamma': 0.25, 'temperature': 4, 'balance': 0.01, 'loss_iter': 0, 'alpha': 2.0, 'eta': 0.1, 'batch_size_new': 0, 'select_sessions': [], 'not_data_init': False, 'set_no_val': False, 'num_workers': 8, 'debug': False, 'model_dir': None, 'use_wandb': False, 'wandb_project': 'origin-fact', 'wandb_entity': '', 'wandb_group': '', 'wandb_run_name': '', 'wandb_tags': [], 'wandb_mode': 'online', 'wandb_watch': 'gradients', 'wandb_watch_freq': 100, 'pin_memory': True, 'base_class': 4, 'num_classes': 10, 'way': 1, 'shot': 5, 'sessions': 7, 'Dataset'

In [6]:
print("=" * 10)
trainset, trainloader, testloader = get_dataloader(args, 0)
for i, batch in enumerate(trainloader, 1):
    data, train_label = [_.to(args.device) for _ in batch]
    print(i)
    label = train_label.cpu().numpy()
    print(np.unique(label))
    if i > 5:
        break


for i in range(1, 7):
    print("=" * 10, i, )
    trainset, trainloader, testloader = get_dataloader(args, i)
    for i, batch in enumerate(trainloader, 1):
        data, train_label = [_.to(args.device) for _ in batch]
        print(i)
        # print(data)
        print(train_label)
    

[0 1 2 3]
[0 1 2 3]
[0 1 2 3]
[0 1 2 3]
1
[0 2 3]
2
[0 2 3]
3
[0 2 3]
4
[0 2 3]
5
[0 2 3]
6
[0 2 3]
========== 1
[4]
[4]
[0 1 2 3 4]
[0 1 2 3 4]
1
tensor([4, 4, 4, 4, 4], device='cuda:0')
========== 2
[5]
[5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
1
tensor([5, 5, 5, 5, 5], device='cuda:0')
========== 3
[6]
[6]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6]
1
tensor([6, 6, 6, 6, 6], device='cuda:0')
========== 4
[7]
[7]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]
1
tensor([7, 7, 7, 7, 7], device='cuda:0')
========== 5
[8]
[8]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
1
tensor([8, 8, 8, 8, 8], device='cuda:0')
========== 6
[9]
[9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
1
tensor([9, 9, 9, 9, 9], device='cuda:0')
